-- MySQL Script generated by MySQL Workbench
-- Sun Jun  9 19:02:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Actividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Actividades` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Actividades` (
  `Id_Actividades` INT NOT NULL AUTO_INCREMENT,
  `Nombre Actividad` VARCHAR(20) GENERATED ALWAYS AS () VIRTUAL,
  `Id_Sucursal` INT NOT NULL,
  `Horario de Inicio` TIME GENERATED ALWAYS AS () VIRTUAL,
  `Horario de Finalización` TIME GENERATED ALWAYS AS () VIRTUAL,
  `Profesor` VARCHAR(50) GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`Id_Actividades`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_Actividades_UNIQUE` ON `Actividades` (`Id_Actividades` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Afiliados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Afiliados` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Afiliados` (
  `Id_Afiliados` INT NOT NULL AUTO_INCREMENT,
  `Nombre y Apellido` VARCHAR(50) GENERATED ALWAYS AS () VIRTUAL,
  `Dni` VARCHAR(12) GENERATED ALWAYS AS () VIRTUAL,
  `Dirección` VARCHAR(70) GENERATED ALWAYS AS () VIRTUAL,
  `Teléfono` VARCHAR(20) GENERATED ALWAYS AS (),
  `Email` VARCHAR(45) GENERATED ALWAYS AS (),
  `Fecha de Nacimiento` DATE GENERATED ALWAYS AS (),
  `Fecha de Inscripción` DATE GENERATED ALWAYS AS (),
  `Tipo de Plan` VARCHAR(45) GENERATED ALWAYS AS (),
  `Certificado Médico` BINARY(2) GENERATED ALWAYS AS (),
  `Id_Profesor` INT NOT NULL,
  `Id_Sucursal` INT NOT NULL,
  `Id_Actividad` INT NOT NULL,
  PRIMARY KEY (`Id_Afiliados`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_Afiliados_UNIQUE` ON `Afiliados` (`Id_Afiliados` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Profesores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Profesores` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Profesores` (
  `Id_Profesor` INT NOT NULL AUTO_INCREMENT,
  `Apellido y Nombre` VARCHAR(50) GENERATED ALWAYS AS (),
  `Dni` VARCHAR(12) GENERATED ALWAYS AS () VIRTUAL,
  `Dirección` VARCHAR(70) GENERATED ALWAYS AS (),
  `Teléfono` VARCHAR(20) GENERATED ALWAYS AS () VIRTUAL,
  `Email` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  `Actividad` VARCHAR(45) GENERATED ALWAYS AS (),
  `Id_Sucursal` INT GENERATED ALWAYS AS () VIRTUAL,
  `Horario Entrada` TIME GENERATED ALWAYS AS () VIRTUAL,
  `Horario de Salida` TIME GENERATED ALWAYS AS (),
  `Fecha de contratación` DATE GENERATED ALWAYS AS (),
  PRIMARY KEY (`Id_Profesor`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_Profesores_UNIQUE` ON `Profesores` (`Id_Profesor` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Sucursales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Sucursales` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Sucursales` (
  `Id_Sucursal` INT NOT NULL AUTO_INCREMENT,
  `Dirección` VARCHAR(70) GENERATED ALWAYS AS () VIRTUAL,
  `Teléfono` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  `Email` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  `Encargado` VARCHAR(45) GENERATED ALWAYS AS () VIRTUAL,
  `Horario de Apertura` TIME GENERATED ALWAYS AS () VIRTUAL,
  `Horario de Cierre` TIME GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`Id_Sucursal`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `Id_Sucursal_UNIQUE` ON `Sucursales` (`Id_Sucursal` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Placeholder table for view `view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `view1` (`id` INT);
SHOW WARNINGS;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------
DROP  IF EXISTS `routine1`;
SHOW WARNINGS;

DELIMITER $$
$$

DELIMITER ;
SHOW WARNINGS;

-- -----------------------------------------------------
-- View `view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `view1`;
SHOW WARNINGS;
DROP VIEW IF EXISTS `view1` ;
SHOW WARNINGS;
SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
